# ==============================================================================
# INSTRUÇÕES PARA O WORKSHOP - SIGA OS 2 PASSOS ABAIXO:
# ==============================================================================

# PASSO 1: DAR UM NOME ÚNICO AO SEU SITE
#   - Pressione 'Ctrl+F' para abrir "Localizar e Substituir".
#   - No campo "Localizar", digite: igor-bonacini
#   - No campo "Substituir", digite um nome único para você.
#     IMPORTANTE: Use apenas letras minúsculas, números e hífens.
#     Exemplos válidos: charles-alencar, pedro-teixeira, site-da-ana
#   - Clique em "Substituir Todos".

# PASSO 2: ALTERAR A SUA MENSAGEM
#   - Encontre a linha que começa com "  index.html:" e altere a mensagem.
# ==============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: igor-bonacini-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Workshop K8s</title>
      <style>
        body { font-family: Arial, sans-serif; text-align: center; margin-top: 50px; background-color: #282c34; color: white;}
        h1 { color: #61dafb; }
      </style>
    </head>
    <body>
      <h1>Hello my friend, tá bão?</h1>
      <p>Bem-vindo ao novo site!</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: igor-bonacini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igor-bonacini
  template:
    metadata:
      labels:
        app: igor-bonacini
    spec:
      containers:
      - name: web
        image: nginx:latest # Usando a imagem oficial e estável do NGINX
        ports:
        - containerPort: 80
        volumeMounts: # Monta o nosso arquivo de mensagem dentro do container
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes: # Define o volume usando o nosso ConfigMap
      - name: html-volume
        configMap:
          name: igor-bonacini-config
---
apiVersion: v1
kind: Service
metadata:
  name: igor-bonacini-service
spec:
  type: ClusterIP
  selector:
    app: igor-bonacini
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: igor-bonacini-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /igor-bonacini
        pathType: Prefix
        backend:
          service:
            name: igor-bonacini-service
            port:
              number: 80
